# Generated by Django 3.2.7 on 2021-09-12 13:56

from django.db import migrations, models
import django_jalali.db.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('section', models.CharField(choices=[("('1', 'دبستان')", 'Elementary'), ("('2', 'متوسطه اول')", 'First Highschool'), ('3', 'متوسطه دوم')], default="('1', 'دبستان')", max_length=30, verbose_name='مقطع تحصیلی')),
                ('grade', models.CharField(choices=[("('1', 'اول')", 'First'), ("('2', 'دوم')", 'Second'), ("('3', 'سوم')", 'Third'), ("('4', 'چهارم')", 'Fourth'), ("('5', 'پنجم')", 'Fifth'), ("('6', 'ششم')", 'Sixth'), ("('7', 'هفتم')", 'Seventh'), ("('8', 'هشتم')", 'Eighth'), ("('9', 'نهم')", 'Ninth'), ("('10', 'دهم')", 'Tenth'), ("('11', 'یازدهم')", 'Eleventh'), ('12', 'دوازدهم')], default="('1', 'اول')", max_length=30, verbose_name='پایه تحصیلی')),
                ('study_field', models.CharField(choices=[("('math', 'ریاضی')", 'Math'), ("('experimental', 'تجربی')", 'Experimental'), ('humanities', 'انسانی')], default="('math', 'ریاضی')", max_length=30, verbose_name='رشته تحصیلی')),
                ('publication_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ نشر')),
                ('publisher', models.CharField(max_length=150, verbose_name='ناشر')),
                ('pdf', models.FileField(upload_to='books/', verbose_name='فایل کتاب')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس کتاب')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
