# Generated by Django 3.2.7 on 2021-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(choices=[("('1', 'اول')", 'First'), ("('2', 'دوم')", 'Second'), ("('3', 'سوم')", 'Third'), ("('4', 'چهارم')", 'Fourth'), ("('5', 'پنجم')", 'Fifth'), ("('6', 'ششم')", 'Sixth'), ("('7', 'هفتم')", 'Seventh'), ("('8', 'هشتم')", 'Eighth'), ("('9', 'نهم')", 'Ninth'), ("('10', 'دهم')", 'Tenth'), ("('11', 'یازدهم')", 'Eleventh'), ('12', 'دوازدهم')], max_length=30, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(choices=[("('1', 'دبستان')", 'Elementary'), ("('2', 'متوسطه اول')", 'First Highschool'), ('3', 'متوسطه دوم')], max_length=30, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='study_field',
            field=models.CharField(choices=[("('math', 'ریاضی')", 'Math'), ("('experimental', 'تجربی')", 'Experimental'), ('humanities', 'انسانی')], max_length=30, verbose_name='رشته تحصیلی'),
        ),
    ]
