# Generated by Django 3.2.7 on 2021-09-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210912_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.book'),
        ),
    ]
