# Generated by Django 3.2.7 on 2021-09-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_chapter_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number',)},
        ),
    ]
